### PR TITLE
HS shows incorrectly under match history

### PR DESCRIPTION
**Pull request by djlarsu**
https://analytikill.com/players/ry%5E_%5E for instance match id 3183 shows 6% headshot, but was actually 6 of 14 kills.  This updates to show the percentage as expected

### CODE REVIEW

**Comment by darkstars31** [comment]
I love this change and want to get it incorporated. I am having a bit of an issue with the merge conflict on the package-lock.json for some reason. I'll try to get back to this asap!

**Comment by djlarsu** [comment]
Feel free to toss that if it's trouble.  I did a npm audit fix just to
update dependencies, but it's not necessary.

**Comment by djlarsu** [comment]
I reverted the npm update

**Review by darkstars31 — APPROVED** [review]
Looks good to me!

**Comment by darkstars31** [comment]
Thanks for fixing this. It's been bugging me for a while but I wasn't sure exactly what HS value was - for some reason I thought it was headshot accuracy out of total shots fired. Never investigated further so this is a great help.

**Pull request merged**
